  apiVersion: v1
  kind: Secret
  metadata:
    name: 'cluster1'
    labels:
      app: kubez
    annotations: {}
    namespace: kubez
  stringData:
    annotations: ''
    clusterid: 'cluster1'
    clustername: '演示集群'
    version: 'k3s'
    clusterconfig: YXBpVmVyc2lvbjogdjEKY2x1c3RlcnM6Ci0gY2x1c3RlcjoKICAgIGNlcnRpZmljYXRlLWF1dGhvcml0eS1kYXRhOiBMUzB0TFMxQ1JVZEpUaUJEUlZKVVNVWkpRMEZVUlMwdExTMHRDazFKU1VKa2FrTkRRVkl5WjBGM1NVSkJaMGxDUVVSQlMwSm5aM0ZvYTJwUFVGRlJSRUZxUVdwTlUwVjNTSGRaUkZaUlVVUkVRbWh5VFROTmRHTXlWbmtLWkcxV2VVeFhUbWhSUkVVelRVUm5NVTVxYXpGTmFrVjNTR2hqVGsxcVVYZE5ha2w1VFVSSmVrOUVVWGhYYUdOT1RYcFJkMDFxUlRWTlJFbDZUMFJSZUFwWGFrRnFUVk5GZDBoM1dVUldVVkZFUkVKb2NrMHpUWFJqTWxaNVpHMVdlVXhYVG1oUlJFVXpUVVJuTVU1cWF6Rk5ha1YzVjFSQlZFSm5ZM0ZvYTJwUENsQlJTVUpDWjJkeGFHdHFUMUJSVFVKQ2QwNURRVUZUY1N0VE1uTlRlVE5JUzFZMVNGRk5hekpGWVV4MU4wbE5kSEJWWjFsT2QyTTNabXBQWmxCSFdrMEtWMDVVY21ka2FtSkRUR1pyY0hoVVZWTTJaREZVYTJkb09HeEtjQ3N6ZDNaaGNFOUZkVEIxWTA5aFRITnZNRWwzVVVSQlQwSm5UbFpJVVRoQ1FXWTRSUXBDUVUxRFFYRlJkMFIzV1VSV1VqQlVRVkZJTDBKQlZYZEJkMFZDTDNwQlpFSm5UbFpJVVRSRlJtZFJWVzV4TjI1bFJ6UnBXWFZaVERaVFVsUlZVekJ3Q2tnNWVUUkVXR3QzUTJkWlNVdHZXa2w2YWpCRlFYZEpSRkozUVhkU1FVbG5XVkJvVWl0RWNWbFhXVFJ5ZVdWSGNEaG1UbUZTTUdWaVdtOXFkV0ZYZFhnS1RITlBiWGcxUTJWc1JtdERTVWhTWkhsTVdrSkdPWGgyZGsxWU0xbFpVaXRDZGxCcU5YSjFUa0pZVFN0VWF6azVSVEJqY25ZcmVqTUtMUzB0TFMxRlRrUWdRMFZTVkVsR1NVTkJWRVV0TFMwdExRbz0KICAgIHNlcnZlcjogaHR0cHM6Ly8xMC4xLjg4LjI6NjQ0MwogIG5hbWU6IGRlZmF1bHQKY29udGV4dHM6Ci0gY29udGV4dDoKICAgIGNsdXN0ZXI6IGRlZmF1bHQKICAgIHVzZXI6IGRlZmF1bHQKICBuYW1lOiBkZWZhdWx0CmN1cnJlbnQtY29udGV4dDogZGVmYXVsdApraW5kOiBDb25maWcKcHJlZmVyZW5jZXM6IHt9CnVzZXJzOgotIG5hbWU6IGRlZmF1bHQKICB1c2VyOgogICAgY2xpZW50LWNlcnRpZmljYXRlLWRhdGE6IExTMHRMUzFDUlVkSlRpQkRSVkpVU1VaSlEwRlVSUzB0TFMwdENrMUpTVUpyVkVORFFWUmxaMEYzU1VKQlowbEpVMXBqVlZwR1lYbGtNM04zUTJkWlNVdHZXa2w2YWpCRlFYZEpkMGw2UldoTlFqaEhRVEZWUlVGM2Qxa0tZWHBPZWt4WFRuTmhWMVoxWkVNeGFsbFZRWGhPZWtFMFRsUlpOVTVVU1hoTlFqUllSRlJKTUUxRVNYbE5ha0Y1VFhwbk1FMVdiMWhFVkVreFRVUkplUXBOVkVGNVRYcG5NRTFXYjNkTlJFVllUVUpWUjBFeFZVVkRhRTFQWXpOc2VtUkhWblJQYlRGb1l6TlNiR051VFhoR1ZFRlVRbWRPVmtKQlRWUkVTRTQxQ21NelVteGlWSEJvV2tjeGNHSnFRbHBOUWsxSFFubHhSMU5OTkRsQlowVkhRME54UjFOTk5EbEJkMFZJUVRCSlFVSkJOREpPVldGcksxRkRiSGxqUVRnS05rd3JhMWRWY21wcmRXbGhiMGh4TmpsdlVtMDBhQzlsTDNOaFRURlFOV2RNVjFGVmVsZFNZMDlDVlhONGRWQmljbUpPZFZrcmVtUmlhbEF6WWxkME1nb3JLMFpqUTNJMmFsTkVRa2ROUVRSSFFURlZaRVIzUlVJdmQxRkZRWGRKUm05RVFWUkNaMDVXU0ZOVlJVUkVRVXRDWjJkeVFtZEZSa0pSWTBSQmFrRm1Da0puVGxaSVUwMUZSMFJCVjJkQ1VYRjFNamhGVm10akwybE1kV1kzVjJObU1WUk5ObFpZVTFSQlJFRkxRbWRuY1docmFrOVFVVkZFUVdkT1NVRkVRa1lLUVdsRlFYVk9kMGRZVWsxQ2IyUTRjVEZDSzJzd1VsRXZiMjlrVlVGSFYyeERRa3RaWlVSTVZsTlZZbTFrUkhORFNVZHVjblEyU2pGTVNuUjFRMWxWVkFwRE9URjJWWFYxTUhOWE0xaE1NRWN6TVZVMlREVjBWVUpxWVRZckNpMHRMUzB0UlU1RUlFTkZVbFJKUmtsRFFWUkZMUzB0TFMwS0xTMHRMUzFDUlVkSlRpQkRSVkpVU1VaSlEwRlVSUzB0TFMwdENrMUpTVUprYWtORFFWSXlaMEYzU1VKQlowbENRVVJCUzBKblozRm9hMnBQVUZGUlJFRnFRV3BOVTBWM1NIZFpSRlpSVVVSRVFtaHlUVE5OZEZreWVIQUtXbGMxTUV4WFRtaFJSRVV6VFVSbk1VNXFhekZOYWtWM1NHaGpUazFxVVhkTmFrbDVUVVJKZWs5RVVYaFhhR05PVFhwUmQwMXFSVFZOUkVsNlQwUlJlQXBYYWtGcVRWTkZkMGgzV1VSV1VWRkVSRUpvY2swelRYUlpNbmh3V2xjMU1FeFhUbWhSUkVVelRVUm5NVTVxYXpGTmFrVjNWMVJCVkVKblkzRm9hMnBQQ2xCUlNVSkNaMmR4YUd0cVQxQlJUVUpDZDA1RFFVRlJaSE50YVdWemJESTNVM2RPZWk5cmR6WjZPVFJZWjBoWlQyNWxjMWhIYkdzemNURTFhMXBCZUdRS1VYVlFURzVVZVdsTk1uTjJkRVZyVEdOamVYWlhObWRDZVZsUlFrWlRaR3hqUlZSTWFFZEVWMlIzZUhCdk1FbDNVVVJCVDBKblRsWklVVGhDUVdZNFJRcENRVTFEUVhGUmQwUjNXVVJXVWpCVVFWRklMMEpCVlhkQmQwVkNMM3BCWkVKblRsWklVVFJGUm1kUlZVdHlkSFpDUmxwSVVEUnBOMjRyTVc1SU9WVjZDazlzVmpCcmQwRjNRMmRaU1V0dldrbDZhakJGUVhkSlJGSjNRWGRTUVVsblNFUlJjbUppV1Zsc1NDdHNaVGhqWnpRNWFFcFNablJzV2pZME1ra3hhR2NLYXpCaFNYTlRNbkppYm5kRFNVSXplRGtyWTNoWlZWVkllR1JWU1c1WFNtSllaR1p0YlVsdU9YSlpWSFkzTW5SNWJHTmpVWE5tWjNrS0xTMHRMUzFGVGtRZ1EwVlNWRWxHU1VOQlZFVXRMUzB0TFFvPQogICAgY2xpZW50LWtleS1kYXRhOiBMUzB0TFMxQ1JVZEpUaUJGUXlCUVVrbFdRVlJGSUV0RldTMHRMUzB0Q2sxSVkwTkJVVVZGU1Vkbk1VazBiWGhDVEVoc2RrbGlhREZuVkhKTU0wMUJWbTVaVWs5SmRUZHhRemd3V1VrMGJuazJNa3h2UVc5SFEwTnhSMU5OTkRrS1FYZEZTRzlWVVVSUlowRkZSR3BaTVZKeFZEVkJTMWhLZDBSNmIzWTJVbHBUZFU5VE5rcHhaMlZ5Y2pKb1IySnBTRGszSzNodmVsVXZiVUYwV2tKVVRncGFSbmMwUmxONlJ6UTVkWFJ6TWpWcU4wNHhkVTB2WkhSaE0ySTNORlozUzNablBUMEtMUzB0TFMxRlRrUWdSVU1nVUZKSlZrRlVSU0JMUlZrdExTMHRMUW89Cg==
  type: Opaque
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: kubez-configmap
  namespace: default
data:
  config.yaml: |-
    logs:
      level: debug
      timeformat: 2006/1/02 15:04:05
      showcaller: false
    program:
      # 后端程序运行的端口号
      port: 8080
      # 
      jwtsecret: jwtHello
      username: admin
      password: 123
      kubeconfig: YXBpVmVyc2lvbjogdjEKY2x1c3RlcnM6Ci0gY2x1c3RlcjoKICAgIGNlcnRpZmljYXRlLWF1dGhvcml0eS1kYXRhOiBMUzB0TFMxQ1JVZEpUaUJEUlZKVVNVWkpRMEZVUlMwdExTMHRDazFKU1VKa2FrTkRRVkl5WjBGM1NVSkJaMGxDUVVSQlMwSm5aM0ZvYTJwUFVGRlJSRUZxUVdwTlUwVjNTSGRaUkZaUlVVUkVRbWh5VFROTmRHTXlWbmtLWkcxV2VVeFhUbWhSUkVVelRVUm5NVTVxYXpGTmFrVjNTR2hqVGsxcVVYZE5ha2w1VFVSSmVrOUVVWGhYYUdOT1RYcFJkMDFxUlRWTlJFbDZUMFJSZUFwWGFrRnFUVk5GZDBoM1dVUldVVkZFUkVKb2NrMHpUWFJqTWxaNVpHMVdlVXhYVG1oUlJFVXpUVVJuTVU1cWF6Rk5ha1YzVjFSQlZFSm5ZM0ZvYTJwUENsQlJTVUpDWjJkeGFHdHFUMUJSVFVKQ2QwNURRVUZUY1N0VE1uTlRlVE5JUzFZMVNGRk5hekpGWVV4MU4wbE5kSEJWWjFsT2QyTTNabXBQWmxCSFdrMEtWMDVVY21ka2FtSkRUR1pyY0hoVVZWTTJaREZVYTJkb09HeEtjQ3N6ZDNaaGNFOUZkVEIxWTA5aFRITnZNRWwzVVVSQlQwSm5UbFpJVVRoQ1FXWTRSUXBDUVUxRFFYRlJkMFIzV1VSV1VqQlVRVkZJTDBKQlZYZEJkMFZDTDNwQlpFSm5UbFpJVVRSRlJtZFJWVzV4TjI1bFJ6UnBXWFZaVERaVFVsUlZVekJ3Q2tnNWVUUkVXR3QzUTJkWlNVdHZXa2w2YWpCRlFYZEpSRkozUVhkU1FVbG5XVkJvVWl0RWNWbFhXVFJ5ZVdWSGNEaG1UbUZTTUdWaVdtOXFkV0ZYZFhnS1RITlBiWGcxUTJWc1JtdERTVWhTWkhsTVdrSkdPWGgyZGsxWU0xbFpVaXRDZGxCcU5YSjFUa0pZVFN0VWF6azVSVEJqY25ZcmVqTUtMUzB0TFMxRlRrUWdRMFZTVkVsR1NVTkJWRVV0TFMwdExRbz0KICAgIHNlcnZlcjogaHR0cHM6Ly8xMC4xLjg4LjI6NjQ0MwogIG5hbWU6IGRlZmF1bHQKY29udGV4dHM6Ci0gY29udGV4dDoKICAgIGNsdXN0ZXI6IGRlZmF1bHQKICAgIHVzZXI6IGRlZmF1bHQKICBuYW1lOiBkZWZhdWx0CmN1cnJlbnQtY29udGV4dDogZGVmYXVsdApraW5kOiBDb25maWcKcHJlZmVyZW5jZXM6IHt9CnVzZXJzOgotIG5hbWU6IGRlZmF1bHQKICB1c2VyOgogICAgY2xpZW50LWNlcnRpZmljYXRlLWRhdGE6IExTMHRMUzFDUlVkSlRpQkRSVkpVU1VaSlEwRlVSUzB0TFMwdENrMUpTVUpyVkVORFFWUmxaMEYzU1VKQlowbEpVMXBqVlZwR1lYbGtNM04zUTJkWlNVdHZXa2w2YWpCRlFYZEpkMGw2UldoTlFqaEhRVEZWUlVGM2Qxa0tZWHBPZWt4WFRuTmhWMVoxWkVNeGFsbFZRWGhPZWtFMFRsUlpOVTVVU1hoTlFqUllSRlJKTUUxRVNYbE5ha0Y1VFhwbk1FMVdiMWhFVkVreFRVUkplUXBOVkVGNVRYcG5NRTFXYjNkTlJFVllUVUpWUjBFeFZVVkRhRTFQWXpOc2VtUkhWblJQYlRGb1l6TlNiR051VFhoR1ZFRlVRbWRPVmtKQlRWUkVTRTQxQ21NelVteGlWSEJvV2tjeGNHSnFRbHBOUWsxSFFubHhSMU5OTkRsQlowVkhRME54UjFOTk5EbEJkMFZJUVRCSlFVSkJOREpPVldGcksxRkRiSGxqUVRnS05rd3JhMWRWY21wcmRXbGhiMGh4TmpsdlVtMDBhQzlsTDNOaFRURlFOV2RNVjFGVmVsZFNZMDlDVlhONGRWQmljbUpPZFZrcmVtUmlhbEF6WWxkME1nb3JLMFpqUTNJMmFsTkVRa2ROUVRSSFFURlZaRVIzUlVJdmQxRkZRWGRKUm05RVFWUkNaMDVXU0ZOVlJVUkVRVXRDWjJkeVFtZEZSa0pSWTBSQmFrRm1Da0puVGxaSVUwMUZSMFJCVjJkQ1VYRjFNamhGVm10akwybE1kV1kzVjJObU1WUk5ObFpZVTFSQlJFRkxRbWRuY1docmFrOVFVVkZFUVdkT1NVRkVRa1lLUVdsRlFYVk9kMGRZVWsxQ2IyUTRjVEZDSzJzd1VsRXZiMjlrVlVGSFYyeERRa3RaWlVSTVZsTlZZbTFrUkhORFNVZHVjblEyU2pGTVNuUjFRMWxWVkFwRE9URjJWWFYxTUhOWE0xaE1NRWN6TVZVMlREVjBWVUpxWVRZckNpMHRMUzB0UlU1RUlFTkZVbFJKUmtsRFFWUkZMUzB0TFMwS0xTMHRMUzFDUlVkSlRpQkRSVkpVU1VaSlEwRlVSUzB0TFMwdENrMUpTVUprYWtORFFWSXlaMEYzU1VKQlowbENRVVJCUzBKblozRm9hMnBQVUZGUlJFRnFRV3BOVTBWM1NIZFpSRlpSVVVSRVFtaHlUVE5OZEZreWVIQUtXbGMxTUV4WFRtaFJSRVV6VFVSbk1VNXFhekZOYWtWM1NHaGpUazFxVVhkTmFrbDVUVVJKZWs5RVVYaFhhR05PVFhwUmQwMXFSVFZOUkVsNlQwUlJlQXBYYWtGcVRWTkZkMGgzV1VSV1VWRkVSRUpvY2swelRYUlpNbmh3V2xjMU1FeFhUbWhSUkVVelRVUm5NVTVxYXpGTmFrVjNWMVJCVkVKblkzRm9hMnBQQ2xCUlNVSkNaMmR4YUd0cVQxQlJUVUpDZDA1RFFVRlJaSE50YVdWemJESTNVM2RPZWk5cmR6WjZPVFJZWjBoWlQyNWxjMWhIYkdzemNURTFhMXBCZUdRS1VYVlFURzVVZVdsTk1uTjJkRVZyVEdOamVYWlhObWRDZVZsUlFrWlRaR3hqUlZSTWFFZEVWMlIzZUhCdk1FbDNVVVJCVDBKblRsWklVVGhDUVdZNFJRcENRVTFEUVhGUmQwUjNXVVJXVWpCVVFWRklMMEpCVlhkQmQwVkNMM3BCWkVKblRsWklVVFJGUm1kUlZVdHlkSFpDUmxwSVVEUnBOMjRyTVc1SU9WVjZDazlzVmpCcmQwRjNRMmRaU1V0dldrbDZhakJGUVhkSlJGSjNRWGRTUVVsblNFUlJjbUppV1Zsc1NDdHNaVGhqWnpRNWFFcFNablJzV2pZME1ra3hhR2NLYXpCaFNYTlRNbkppYm5kRFNVSXplRGtyWTNoWlZWVkllR1JWU1c1WFNtSllaR1p0YlVsdU9YSlpWSFkzTW5SNWJHTmpVWE5tWjNrS0xTMHRMUzFGVGtRZ1EwVlNWRWxHU1VOQlZFVXRMUzB0TFFvPQogICAgY2xpZW50LWtleS1kYXRhOiBMUzB0TFMxQ1JVZEpUaUJGUXlCUVVrbFdRVlJGSUV0RldTMHRMUzB0Q2sxSVkwTkJVVVZGU1Vkbk1VazBiWGhDVEVoc2RrbGlhREZuVkhKTU0wMUJWbTVaVWs5SmRUZHhRemd3V1VrMGJuazJNa3h2UVc5SFEwTnhSMU5OTkRrS1FYZEZTRzlWVVVSUlowRkZSR3BaTVZKeFZEVkJTMWhLZDBSNmIzWTJVbHBUZFU5VE5rcHhaMlZ5Y2pKb1IySnBTRGszSzNodmVsVXZiVUYwV2tKVVRncGFSbmMwUmxONlJ6UTVkWFJ6TWpWcU4wNHhkVTB2WkhSaE0ySTNORlozUzNablBUMEtMUzB0TFMxRlRrUWdSVU1nVUZKSlZrRlVSU0JMUlZrdExTMHRMUW89Cg==
       
immutable: false


---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubez
  labels:
    app: kubez
  annotations:
    app: kubez
  namespace: default
spec:
  selector:
    matchLabels:
      app: kubez
  replicas: 1
  template:
    metadata:
      labels:
        app: kubez
      annotations:
        app: kubez
    spec:
      restartPolicy: Always
      dnsPolicy: ClusterFirst
      volumes:
        - name: kubez-config
          configMap:
            name: kubez-configmap
            defaultMode: 420
            optional: true
      containers:
        - name: kubez
          image: reactive0/kubez:latest
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: kubez-config
              mountPath: /kubez/config.yaml
              subPath: config.yaml

---
apiVersion: v1
kind: Service
metadata:
  name: kubez
  namespace: default
  labels: {}
  annotations: {}
spec:
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: kubez
  selector:
    app: kubez
  type: ClusterIP
  sessionAffinity: None
---
apiVersion: v1
kind: Service
metadata:
  name: kubez-frontend
  namespace: default
  labels:
    app: kubez-frontend
spec:
  ports:
    - name: kubez-frontend
      protocol: TCP
      port: 8080
      targetPort: 80
      nodePort: 30261
  selector:
    app: kubez-frontend
  type: NodePort
  sessionAffinity: None

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubez-frontend
  namespace: default
  labels:
    app: kubez-frontend
  annotations:
    app: kubez-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kubez-frontend
  template:
    metadata:
      labels:
        app: kubez-frontend
      annotations:
        app: kubez-frontend
    spec:
      containers:
        - name: kubez-frontend
          image: reactive0/kubez_frontend:latest
          ports:
            - name: kubez-frontend
              containerPort: 80
              protocol: TCP
          imagePullPolicy: Always
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
