name: Upload Go test results

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21.4'

      - name: Install dependencies
        run: go get .

      - name: Build
        run: go build -v -o kubez . 

      - name: ls
        run: ls

      - name: ls
        run: ls ${{ github.workspace }}

      - name: login docker
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: docker meta
        id: meta
        uses: docker/metadata-action@v5

